### ISSUE TITLE
Solution

### ISSUE THREAD

**Issue by control-toolbox** [control-toolbox/CTOptimisation.jl#9]
Ajouter dans la solution, la méthode qui a été utilisée pour résoudre. Cela permettra de faire des tests (vérifier si l'appel est correct) même dans le package `OptimalControl`.

**Comment by ocots** [comment]
Voir [LabelledArrays](https://github.com/SciML/LabelledArrays.jl#example-nice-diffeq-syntax-without-a-dsl)

**Comment by ocots** [comment]
Voir aussi [Issue](https://github.com/control-toolbox/control-toolbox.github.io/issues/12)
